# Generated by Django 2.2.28 on 2022-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment',
            field=models.ManyToManyField(to='track.Appointment'),
        ),
    ]
