# Generated by Django 2.2.28 on 2022-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20220523_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='food_list',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(default=48578, primary_key=True, serialize=False),
        ),
    ]
