# Generated by Django 4.0.4 on 2022-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(default=6652, primary_key=True, serialize=False),
        ),
    ]
