# Generated by Django 3.0.5 on 2022-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20220412_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/Food/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/NurseProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/PatientProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
