# Generated by Django 3.0.5 on 2022-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20220523_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(default=98181, primary_key=True, serialize=False),
        ),
    ]
