# Generated by Django 4.0.3 on 2022-05-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_food_id_alter_medication_id_alter_nurse_id_and_more'),
        ('track', '0008_feedback'),
    ]

    operations = [
    ]
