# Generated by Django 3.0.5 on 2022-05-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_feedback'),
        ('track', '0004_alter_food_id_alter_medication_id_alter_nurse_id_and_more'),
    ]

    operations = [
    ]
