# Generated by Django 3.0.5 on 2022-05-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_merge_20220506_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='dosage',
            new_name='numOftimes',
        ),
        migrations.AddField(
            model_name='medication',
            name='Description',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='expiratDate',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
