# Generated by Django 4.0.3 on 2022-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_merge_20220507_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Glucose',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
