# Generated by Django 3.0.5 on 2022-05-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_auto_20220523_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(default=26876, primary_key=True, serialize=False),
        ),
    ]
