# Generated by Django 3.0.5 on 2022-05-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20220507_0407'),
        ('track', '0010_patient_glucose_alter_feedback_id'),
    ]

    operations = [
    ]
