# Generated by Django 3.0.5 on 2022-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20220523_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(default=86278, primary_key=True, serialize=False, unique=True),
        ),
    ]
