# Generated by Django 3.0.5 on 2022-05-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_auto_20220508_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='reports',
            field=models.ManyToManyField(to='track.Medication'),
        ),
    ]
