# Generated by Django 3.0.5 on 2022-05-23 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_auto_20220523_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(default=uuid.UUID('8034928f-dd5f-40b1-9898-5be47f5b8be9'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
