# Generated by Django 3.0.5 on 2022-05-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_auto_20220508_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='reports',
            field=models.ManyToManyField(to='track.Record'),
        ),
    ]
