# Generated by Django 3.0.5 on 2022-05-23 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_auto_20220523_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(default=uuid.UUID('0c9c58c5-9a44-43bb-9477-b645f4b01e8f'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
