# Generated by Django 3.0.5 on 2022-05-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_auto_20220508_0559'),
        ('track', '0013_patient_feedbacks'),
    ]

    operations = [
    ]
