# Generated by Django 4.0.4 on 2022-05-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_patient_feedbacks'),
        ('track', '0014_auto_20220508_0559'),
    ]

    operations = [
    ]
