# Generated by Django 3.0.5 on 2022-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0015_merge_20220508_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Glucose',
            field=models.IntegerField(default=80),
        ),
    ]
