# Generated by Django 4.0.3 on 2022-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0016_patient_ecg_patient_glucose_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='replay',
            field=models.CharField(default='There is no response to this message', max_length=500),
        ),
    ]
