# Generated by Django 3.0.5 on 2022-05-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0016_patient_ecg_patient_glucose_alter_feedback_id_and_more'),
        ('track', '0016_patient_glucose'),
    ]

    operations = [
    ]
