# Generated by Django 2.2.28 on 2022-05-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0017_alter_feedback_replay'),
        ('track', '0017_merge_20220510_1058'),
    ]

    operations = [
    ]
