# Generated by Django 2.2.28 on 2022-05-16 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0019_auto_20220515_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 16, 7, 52, 14, 14930)),
        ),
    ]
