# Generated by Django 2.2.28 on 2022-05-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0020_auto_20220516_0752'),
        ('track', '0020_alter_appointment_id_alter_appointment_time_and_more'),
    ]

    operations = [
    ]
